### ISSUE TITLE
Publicar pacote no NPM

### ISSUE THREAD

**Issue by lesleyandrez** [lesimoes/bostinho#1]
Primeiro parabéns e obrigado por deixar esse projeto open source!
Simples e eficiente, quero começar a usar nos meus projetos agora.

**Sugestão:**
Poderia publicar essa API de chatbots como um pacote NPM.

**Comment by lesimoes** [comment]
Boa! Ainda não tinha pensado nisso! Vou fazer uns ajustes e coloco lá.

Obrigado pela sugestão

**Comment by sealabr** [comment]
Tendiiiii

**Comment by lesimoes** [comment]
Saí da minha issue

**Comment by lesimoes** [comment]
Tá na mão: https://www.npmjs.com/package/bostinho
